sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_f7d1c2265b12_key -iv $encrypted_f7d1c2265b12_iv -in testkubernetesyh-sa.json.enc -out testkubernetesyh-sa.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc 
  - gcloud components update kubectl 
  - gcloud auth activate-service-account -key-file service-account.json 
  - gcloud config set project testkubernetesyh
  - gcloud config set compute/zone us-central1-c 
  - gcloud container clusters get-credentials mkcluster 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build youssefh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true youssefh/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
